name: Analyze templates
on:
  push:
    branches: ["psrule", "psrulefixed"]
jobs:
  analyze_arm:
    name: Analyze templates
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Run PSRule
      - name: Analyze with PSRule
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: PSRule.Rules.Azure